export const sampleProducts = [
  {
    name: "Amiksyn",
    id: "amiksyn",
    price: 100,
    image: "./images/medicine-amiksyn.jpg",
    shops: ["Low Prices Pharmacy", "Good Health!"],
    countInStock: 10,
  },
  {
    name: "Nimid",
    id: "nimid",
    price: 34.99,
    image: "./images/medicine-nimid.jpg",
    shops: ["Fisrt Private", "Good Health!"],
    countInStock: 5,
  },
  {
    name: "Solpadeyin",
    id: "solpadeyin",
    price: 68.25,
    image: "./images/medicine-solpadeyin.jpg",
    shops: ["Fisrt Private"],
    countInStock: 2,
  },
  {
    name: "Strepsils",
    id: "strepsils",
    price: 234,
    image: "./images/medicine-strepsils.jpg",
    shops: ["Low Prices Pharmacy", "Good Health!", "Fisrt Private"],
    countInStock: 6,
  },
  {
    name: "Vitamin C",
    id: "vitamin-c",
    price: 131,
    image: "./images/medicine-vitamin-c.jpg",
    shops: ["Good Health!"],
    countInStock: 0,
  },
  {
    name: "Zinc",
    id: "zinc",
    price: 54,
    image: "./images/medicine-zinc.jpg",
    shops: ["Low Prices Pharmacy", "Good Health!", "Fisrt Private"],
    countInStock: 3,
  },
];
